spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3307/vision_bigdata
    username: root
    password: vision@bigdata
  jackson:
    serialization:
      #保证@ResponseBody时，Date会自动转化为timeStamp的数值(毫秒数)
      WRITE_DATES_AS_TIMESTAMPS : true
    time-zone: GMT+8
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

baseUri: http://localhost:10004/bvs/api/v1/
frsBaseUri: http://localhost:5001/frs/api/v1/

rabbitmq:
  exchange:
    queue: tut.fanout

