spring:
  data:
    neo4j:
      uri: 172.16.6.110:7687
      username: neo4j
      password: 123456
    datasource:
      url: jdbc:mysql://172.16.6.134:3306/vision_bigdata
      username: root
      password: vision@bigdata